-- Cyan SCTV
ALTER TABLE benchmarks ADD COLUMN c_5 REAL;
ALTER TABLE benchmarks ADD COLUMN c_10 REAL;
ALTER TABLE benchmarks ADD COLUMN c_25 REAL;
ALTER TABLE benchmarks ADD COLUMN c_50 REAL;
ALTER TABLE benchmarks ADD COLUMN c_75 REAL;

-- Magenta SCTV
ALTER TABLE benchmarks ADD COLUMN m_5 REAL;
ALTER TABLE benchmarks ADD COLUMN m_10 REAL;
ALTER TABLE benchmarks ADD COLUMN m_25 REAL;
ALTER TABLE benchmarks ADD COLUMN m_50 REAL;
ALTER TABLE benchmarks ADD COLUMN m_75 REAL;

-- Yellow SCTV
ALTER TABLE benchmarks ADD COLUMN y_5 REAL;
ALTER TABLE benchmarks ADD COLUMN y_10 REAL;
ALTER TABLE benchmarks ADD COLUMN y_25 REAL;
ALTER TABLE benchmarks ADD COLUMN y_50 REAL;
ALTER TABLE benchmarks ADD COLUMN y_75 REAL;

-- Black SCTV
ALTER TABLE benchmarks ADD COLUMN k_5 REAL;
ALTER TABLE benchmarks ADD COLUMN k_10 REAL;
ALTER TABLE benchmarks ADD COLUMN k_25 REAL;
ALTER TABLE benchmarks ADD COLUMN k_50 REAL;
ALTER TABLE benchmarks ADD COLUMN k_75 REAL;
