CREATE TABLE jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_number TEXT NOT NULL UNIQUE,
  job_title TEXT NOT NULL,
  press_id INTEGER,
  print_method TEXT,
  color_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active',
  job_state TEXT DEFAULT 'ready',
  target_units INTEGER DEFAULT 0,
  actual_units INTEGER DEFAULT 0,
  waste_units INTEGER DEFAULT 0,
  stops_count INTEGER DEFAULT 0,
  setup_start_at TEXT,
  first_pull_at TEXT,
  production_start_at TEXT,
  completed_at TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE benchmarks (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id          INTEGER,
  created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
  date            TEXT,
  time            TEXT,
  machine         TEXT,       -- Press name
  process_type    TEXT,       -- 'gravure' | 'flexo'
  color_name      TEXT,
  color_hex       TEXT,
  de              REAL,
  ds              REAL,
  delta_c         REAL,
  delta_h         REAL,
  delta_l         REAL,
  viscosity       REAL,
  print_speed     REAL,
  drying_temp     REAL,
  measurement_seq INTEGER,
  status_en       TEXT,
  status_tr       TEXT,
  benchmark_en    TEXT,
  benchmark_tr    TEXT,
  diagnosis_en    TEXT,
  diagnosis_tr    TEXT,
  sctv_5 REAL, sctv_10 REAL, sctv_25 REAL, sctv_50 REAL, sctv_75 REAL,
  edited_at TEXT,
  edited_from TEXT
);
